version: '3'
services:

  nats1:
    image: nats:latest
    ports:
      - '4222:4222'
      - '6222:6222'
    command: -DV -p 4222 -cluster nats://0.0.0.0:6222 -routes nats://ruser:T0pS3cr3t@nats2:6222,nats://ruser:T0pS3cr3t@nats3:6222

  nats2:
    image: nats:latest
    ports:
      - '4223:4222'
      - '6223:6222'
    command: -DV -p 4222 -cluster nats://0.0.0.0:6222 -routes nats://ruser:T0pS3cr3t@nats1:6222,nats://ruser:T0pS3cr3t@nats3:6222

  nats3:
    image: nats:latest
    ports:
      - '4224:4222'
      - '6224:6222'
    command: -DV -p 4222 -cluster nats://0.0.0.0:6222 -routes nats://ruser:T0pS3cr3t@nats1:6222,nats://ruser:T0pS3cr3t@nats2:6222

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: gopass
      POSTGRES_DB: gotest
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

